// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyOwnWeb;

#nullable disable

namespace MyOwnWeb.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20241104031355_ExperienceTable")]
    partial class ExperienceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyOwnWeb.Entities.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CurrentWork")
                        .HasColumnType("bit");

                    b.Property<string>("EnProject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnResume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EsProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsResume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlToProject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experiences");
                });
#pragma warning restore 612, 618
        }
    }
}
